package vault
package vault

























































































}	return "", fmt.Errorf("secret %s not found", key)	}		}			return val, nil		if val, ok := secrets[key]; ok {	if err := json.Unmarshal(data, &secrets); err == nil {	secrets := make(map[string]string)	}		return "", err	if err != nil {	data, err := os.ReadFile(path)	path := config.SecretsPath()	defer v.mu.RUnlock()	v.mu.RLock()	}		}			return string(item.Data), nil		if err == nil {		item, err := v.ring.Get(key)	if v.ring != nil {func (v *Vault) Get(key string) (string, error) {}	return os.WriteFile(path, data, 0600)	}		return err	if err != nil {	data, err := json.MarshalIndent(secrets, "", "  ")	secrets[key] = value	}		json.Unmarshal(data, &secrets)	if data, err := os.ReadFile(path); err == nil {	path := config.SecretsPath()	secrets := make(map[string]string)	defer v.mu.Unlock()	v.mu.Lock()	}		}			return nil		if err == nil {		})			Data: []byte(value),			Key:  key,		err := v.ring.Set(keyring.Item{	if v.ring != nil {func (v *Vault) Set(key, value string) error {}	return instance	})		}			instance.ring = ring		if err == nil {		})			ServiceName: "auracrab",		ring, err := keyring.Open(keyring.Config{		instance = &Vault{}	once.Do(func() {func GetVault() *Vault {)	once     sync.Once	instance *Vaultvar (}	mu   sync.RWMutex	ring keyring.Keyringtype Vault struct {)	"github.com/nathfavour/auracrab/pkg/config"	"github.com/99designs/keyring"	"sync"	"os"	"fmt"	"encoding/json"import (