package cli
package cli

import (























































}	rootCmd.AddCommand(auditCmd)	auditCmd.Flags().StringVarP(&auditFormat, "format", "f", "text", "Output format (text, json)")func init() {}	},		}			fmt.Println()			}				fmt.Printf("   Fix:  %s\n", f.Remediation)			if f.Remediation != "" {			fmt.Printf("   Desc: %s\n", f.Description)			fmt.Printf("%s [%s] %s\n", severityChar, f.Severity, f.Title)			}				severityChar = "🚨"			} else if f.Severity == security.SeverityCritical {				severityChar = "⚠️"			if f.Severity == security.SeverityWarn {			severityChar := "ℹ️"		for _, f := range report.Findings {		}			return			fmt.Println("✅ No findings. Your system looks system-intimate and secure.")		if len(report.Findings) == 0 {		fmt.Println("=== Auracrab Security Audit Report ===")		}			return			fmt.Println(string(data))			data, _ := json.MarshalIndent(report, "", "  ")		if auditFormat == "json" {		}			os.Exit(1)			fmt.Printf("Audit failed: %v\n", err)		if err != nil {		report, err := security.RunAudit()	Run: func(cmd *cobra.Command, args []string) {	Short: "Run security audit on the system and ecosystem",	Use:   "audit",var auditCmd = &cobra.Command{)	auditFormat stringvar ()	"github.com/spf13/cobra"	"github.com/nathfavour/auracrab/pkg/security"	"os"	"fmt"	"encoding/json"