package social
package social

















































}	return list	}		list = append(list, k)	for k := range m.platforms {	var list []stringfunc (m *Manager) ListPlatforms() []string {}	return p, nil	}		return nil, fmt.Errorf("platform %s not supported", name)	if !ok {	p, ok := m.platforms[name]func (m *Manager) GetPlatform(name string) (Platform, error) {}	m.platforms[p.Name()] = pfunc (m *Manager) Register(p Platform) {}	}		platforms: make(map[string]Platform),	return &Manager{func NewManager() *Manager {}	platforms map[string]Platformtype Manager struct {}	URL     string	Content string	Author  string	ID      stringtype Post struct {}	GetFeed(ctx context.Context, limit int) ([]Post, error)	Post(ctx context.Context, content string) (string, error)	Name() stringtype Platform interface {// Platform defines the interface for social media automation.)	"fmt"	"context"import (