package memory
package memory

























































}	_ = os.WriteFile(m.path, data, 0644)	data, _ := json.MarshalIndent(m.Store, "", "  ")func (m *Memory) save() {}	_ = json.Unmarshal(data, &m.Store)	}		return	if err != nil {	data, err := os.ReadFile(m.path)func (m *Memory) load() {}	return val, ok	val, ok := m.Store[key]	defer m.mu.RUnlock()	m.mu.RLock()func (m *Memory) Get(key string) (string, bool) {}	m.save()	m.Store[key] = value	defer m.mu.Unlock()	m.mu.Lock()func (m *Memory) Set(key, value string) {}	return instance	})		instance.load()		}			path:  config.DataDir() + "/memory.json",			Store: make(map[string]string),		instance = &Memory{	once.Do(func() {func GetMemory() *Memory {)	once     sync.Once	instance *Memoryvar (}	mu    sync.RWMutex	path  string	Store map[string]string `json:"store"`type Memory struct {)	"github.com/nathfavour/auracrab/pkg/config"	"sync"	"os"	"encoding/json"import (